name: MMOSpawnPoint
version: '${version}'
main: uz.alex2276564.mmospawnpoint.MMOSpawnPoint
api-version: '1.16'
folia-supported: true
authors: [ alex2276564 ]
description: 'Advanced MMO spawn system with region-based spawns, party respawn mechanics, safe location finding, resource pack integration, and comprehensive condition-based teleportation. Features walking spawn points, waiting rooms, async location search, advanced caching, and extensive customization for MMO servers.'
softdepend: [ WorldGuard, PlaceholderAPI ]
website: https://github.com/alex2276564/MMOSpawnPoint
commands:
  mmospawnpoint:
    description: Main command for MMOSpawnPoint plugin
    usage: /mmospawnpoint <reload|spawnpoint|party|help> [args]
    aliases: [ msp ]
    permission: mmospawnpoint.command
permissions:
  mmospawnpoint.command:
    description: Allows access to basic MMOSpawnPoint commands
    default: op
  mmospawnpoint.reload:
    description: Allows reloading the MMOSpawnPoint configuration
    default: op
  mmospawnpoint.spawnpoint:
    description: Base permission for /msp spawnpoint
    default: op
  mmospawnpoint.spawnpoint.set:
    description: Set bed/anchor spawn
    default: op
  mmospawnpoint.spawnpoint.clear:
    description: Clear bed/anchor spawn
    default: op
  mmospawnpoint.spawnpoint.teleport:
    description: Teleport to bed/anchor spawn
    default: op
  mmospawnpoint.spawnpoint.show:
    description: Show bed/anchor spawn
    default: op
  mmospawnpoint.simulate:
    description: Root permission for simulate command
    default: op
  mmospawnpoint.simulate.death:
    description: Simulate death respawn
    default: op
  mmospawnpoint.simulate.join:
    description: Simulate join teleport
    default: op
  mmospawnpoint.simulate.back:
    description: Return to pre-simulation location
    default: op
  mmospawnpoint.simulate.others:
    description: Allow simulating for other players
    default: op
  mmospawnpoint.cache:
    description: Root permission for cache command
    default: op
  mmospawnpoint.cache.stats:
    description: View cache stats
    default: op
  mmospawnpoint.cache.clear:
    description: Clear cache
    default: op
  mmospawnpoint.party:
    description: Root permission for party command
    default: op
  mmospawnpoint.party.invite:
    description: Allows inviting players to a party
    default: op
  mmospawnpoint.party.accept:
    description: Allows accepting party invitations
    default: op
  mmospawnpoint.party.deny:
    description: Allows denying party invitations
    default: op
  mmospawnpoint.party.leave:
    description: Allows leaving a party
    default: op
  mmospawnpoint.party.list:
    description: Allows listing party members
    default: op
  mmospawnpoint.party.remove:
    description: Allows removing players from a party
    default: op
  mmospawnpoint.party.setleader:
    description: Allows transferring party leadership
    default: op
  mmospawnpoint.party.options:
    description: Root permission for party options command
    default: op
  mmospawnpoint.party.options.mode:
    description: Allows changing party respawn mode
    default: op
  mmospawnpoint.party.options.target:
    description: Allows set party respawn target
    default: op