name: MMOSpawnPoint
version: '${version}'
main: uz.alex2276564.mmospawnpoint.MMOSpawnPoint
api-version: '1.16'
authors: [ alex2276564 ]
description: MMOSpawnPoint is a powerful and flexible Minecraft plugin that revolutionizes how player respawning works on your server. With region-based, world-based, and condition-based spawn points, you can create immersive experiences for your players that go far beyond the vanilla respawn mechanics.
softdepend: [ WorldGuard, PlaceholderAPI ]
website: https://github.com/alex2276564/MMOSpawnPoint
commands:
  mmospawnpoint:
    description: Main command for MMOSpawnPoint plugin
    usage: /mmospawnpoint <reload|setspawnpoint|party|help> [args]
    aliases: [ msp ]
    permission: mmospawnpoint.command
permissions:
  mmospawnpoint.command:
    description: Allows access to basic MMOSpawnPoint commands
    default: true
  mmospawnpoint.reload:
    description: Allows reloading the MMOSpawnPoint configuration
    default: op
  mmospawnpoint.setspawnpoint:
    description: Allows setting vanilla respawn point for players
    default: op
  mmospawnpoint.party.invite:
    description: Allows inviting players to a party
    default: true
  mmospawnpoint.party.accept:
    description: Allows accepting party invitations
    default: true
  mmospawnpoint.party.deny:
    description: Allows denying party invitations
    default: true
  mmospawnpoint.party.leave:
    description: Allows leaving a party
    default: true
  mmospawnpoint.party.list:
    description: Allows listing party members
    default: true
  mmospawnpoint.party.remove:
    description: Allows removing players from a party
    default: true
  mmospawnpoint.party.setleader:
    description: Allows transferring party leadership
    default: true
  mmospawnpoint.party.options:
    description: Allows changing party options
    default: true