name: Feature Request
description: Suggest an idea for MMOSpawnPoint
title: "[Feature]: "
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
        Please provide as much detail as possible about your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see added
      placeholder: A clear and detailed description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the situation where this feature would be useful
      placeholder: |
        This feature would be useful when...
        It would help solve...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: checkboxes
    id: considerations
    attributes:
      label: Additional Considerations
      options:
        - label: This feature would be compatible with WorldGuard
        - label: This feature would be compatible with PlaceholderAPI
        - label: This feature would not impact server performance significantly
        - label: This feature would require configuration options